### ISSUE TITLE
New naming and folders structure

### ISSUE THREAD

**Issue by GildasMorel** [sfeir-open-source/talk-control#16]
New naming :
ensuite-front => remote-control
ensuite-client => client
ensuite-node => server

New folders structure to handle new naming :
- src
   - common
      - event-bus
         - postmessage
         - websockets
      - helpers
   - client
      - engines
   - remote-control
   - server

**Comment by TristanElain** [comment]
Few adjustments have been made :
ensuite-front => talk-control-master
ensuite-client => talk-control-slave
ensuite-node => talk-control-server

Folders structure :
- src
   - common (untouched)
   - client
      - engines
      - talk-control-master
      - talk-control-slave
   - server
