### ISSUE TITLE
Exclude src/client/talk-control-master/dist from coverage (istanbul)

### ISSUE THREAD

**Issue by GildasMorel** [sfeir-open-source/talk-control#20]
Run `npm run coverage`

The folder src/client/talk-control-master/dist should be excluded from coverage.
So, excluding `dist` folders from coverage should resolve this issue.

**Comment by TristanElain** [comment]
La configuration de instabul est dans le `package.json` à l'attribut `"nyc"`. Il est déjà configuré pour ne prendre en compte que les répertoires `src` et `test`.
J'ai fait un test avec `npm run build` puis `npm run coverage`et n'ai eu aucun problème avec le répertoire dist.
Peux-tu me confirmer que le problème n'est plus d'actualité ?

**Comment by GildasMorel** [comment]
Ok, je regarde ça dès que je remets la main sur mon PC sfeir :p

**Comment by GildasMorel** [comment]
Je ne reproduis plus le problème, je close l'issue.
