### ISSUE TITLE
Inject tc-component script in showcase iframe

### ISSUE THREAD

**Issue by GildasMorel** [sfeir-open-source/talk-control#50]
Assume that the speaker has his presentation locally and use TalkControl locally.

- [ ] Ask him to select the path of his presentation
- [ ] Ask him if he accepts that TalkControl update his presentation with tc-slave script
- [ ] Automatically detect and insert tc-slave script into presentation
- [ ] Serve presentation by http

This issue closes #7

**Comment by GildasMorel** [comment]
Regarder File API pour injection script tc-slave

**Comment by GildasMorel** [comment]
Autre possibilité :
- Le speaker renseigne l'url de sa prez
- TalkControl récupère le fichier index.html de la prez (fetch)
- TalkControl remplace les href dont le path est relatif, pour ajouter l'url de la prez
- TalkControl ajoute le tc-component
- TalkControl injecte le tout dans une iframe

**Comment by jefBinomed** [comment]
Autre idée : 
* offrir un script JS qui intègre le tc-component soit derrière un CDN, soit en npm
* Ce dernier en premier lieu écoute un event postmessage (window) pour obtenir les informations de configuration du serveur TalkControl
* La magie opère ensuite

**Comment by GildasMorel** [comment]
Regarder les autres moteurs de prez que l'on veut gérer : Google Slides, Spectacle, etc... pour voir quelle solution s'adapte le mieux :
- Injection manuelle
- Injection auto avec proxy
- Utilisation de la présentation en locale (pas compatible Google Slides)

Cela va permettre de savoir quelle solution s'adapte le mieux, voir éliminer automatiquement des solutions, ce qui serait top.

**Comment by jefBinomed** [comment]
Est ce qu'on met en place les 3 processus ? en gros, j'aurais bien offert la possibilité que le·a speaker·euse intègre lui même le script ?

1. Le·a speaker·euse rentre l'url de sa prez
2. Tc-control fait un ping pour savoir si tc-component est présent
2.1 tc-component est présent -> on lance l'initiatilisation de la prez comme avant
2.2 tc-component n'est pas présent -> On demande l'autorisation à l'utilisateur ce qu'il préfère : 
  * Mode magique mais pouvant avoir quelques soucis sur des prezs avec des appels serveurs à droite à gauche (le mode proxy en gros) -> La personne n'a rien à faire
  * Mode magique dégradé, le·a speaker·euse doit s'assurer que sa prez est bien derrière un serveur en mode no-cors (on peut donner une commande à jouer pour faire). C'est le mode proxy light. La personne doit juste s'assurer que sa prez tourne en mode no-cors
  * Mode manuel -> On invite le·a speaker·euse à injecter le script dans la présentation
3 Si le·a speaker·euse choisi un des modes magiques, on utilise les routes proxy pour gérer l'injection du script. On recharge l'iframe avec le script injecté et on initialise la prez comme avant
4 Si le·a speaker·euse choisi le mode manuel, on vide le champ de saisie url et l'iframe -> On reviendra ainsi à l'étape 1

**Comment by jefBinomed** [comment]
L'injection du script se basera sur ce code là : https://github.com/binomed/WebExperiments/tree/master/IframeCommunication
